### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by codingmanu** [citygml4j/citygml-tools#1]
I'm interested on running the GML -> JSON module but I'm not familiar with gradle. 

Do I have to just execute the CityGMLTools.java file? I use NetBeans as my IDE.

**Comment by clausnagel** [comment]
Yes, documenting the use of `citygml-tools` is an open item on my todo list...

I built a [pre-release](https://github.com/citygml4j/citygml-tools/releases/tag/v0.5) that you can use. Just download and unzip to your local file system. Open a shell and change to the root directory where you unzipped the tools. From there, issue the following command:

    > bin/citygml-tools -h

This will print a short help to the console. For a conversion from CityGML to CityJSON, use the subcommand `to-cityjson`. The following command provides details on how to use `to-cityjson`: 

    > bin/citygml-tools to-cityjson -h

Well, that's it. You can also run `citygml-tools` from within Netbeans. Then indeed `CityGMLTools.java` is the class to execute. Note that you have to provide all command line parameters in the run dialog of Netbeans (sorry, I'm not a Netbeans user but am sure this should be simple).

Hope this helps.

**Comment by clausnagel** [comment]
Btw, if you want to build yourself, simply clone the repository to your local file system and run the following Gradle command from the root of the repository.

    > gradlew installDist

The `citygml-tools` package will be available under `citygml-tools/build/install`.

**Comment by codingmanu** [comment]
Thanks! The pre-release works perfect. I was having trouble building my own (install folder doesn't get created). I'll investigate more in case there's something wrong with my Java config.
