### ISSUE TITLE
Set the encoding of the output file

### ISSUE THREAD

**Issue by masgra** [citygml4j/citygml-tools#15]
Including an option to set the encoding of characters in the output file when passing "to-cityjson". 

As for now, umlaut (ä,ö,ü) and other special characters, like "ß" are written to the output file with the unknown character  (U+FFFD).

**Comment by clausnagel** [comment]
Thanks, makes absolutely sense. And it should be available for all commands that create output files. I will use "UTF-8" as default.

**Comment by clausnagel** [comment]
Fixed in bb217aae978a9621cb9bb8a0026db75610bf8fd4

**Comment by masgra** [comment]
> 
> 
> Fixed in [bb217aa](https://github.com/citygml4j/citygml-tools/commit/bb217aae978a9621cb9bb8a0026db75610bf8fd4)

Awesome! It workes perfectly!
