### ISSUE TITLE
from-cityjson plantcover-geometry ignored

### ISSUE THREAD

**Issue by mvangog** [citygml4j/citygml-tools#17]
Hi,

I am using citygml-tools-1.4.0
when converting a cityjson to citygml with citygml-tools from-cityjson the geometry of CityObjects of type PlantCover is ignored. resulting in a cityObjectmember veg:PlantCover without geometry in the cityGML-file.

as far as i know, the cityjson-file is valid. 
the geometry-type of the Plantcover-objects is MultiSurface, which is allowed according to the ciyjson specification.

when i change the type of the CityObjects to LandUse in a textEditor, converting the file results in a cityGML-file that does contain the geometry.

you can find a subset of the citymodel in the file plantcover-subset.json at https://github.com/martijnvangog/cityjson

thanks

**Comment by clausnagel** [comment]
Thanks for reporting and providing a test dataset. You found a bug in the citygml4j library that is used by citygml-tools. I fixed the bug there in `master` (https://github.com/citygml4j/citygml4j/commit/61f420dd765fd581d3fbd8bd4c36022a8a18cd6a). I tested with your dataset and the result looks fine.

I will post here when an update of citygml-tools is available. I have to publish a bugfix release for citygml4j first, so it will take me some more time.

If you want to benefit from the fix immediately, you can simply build a new version of citygml4j from `master` following [this instruction](https://github.com/citygml4j/citygml4j#building). Afterwards, replace the `citygml4j-<version>.jar` in the `lib` folder of citygml-tools with your own build.

**Comment by mvangog** [comment]
great, Thanks!

**Comment by clausnagel** [comment]
Just released [version 1.4.1](https://github.com/citygml4j/citygml-tools/releases/tag/v1.4.1) that contains the bugfix. So, closing this issue.
