### ISSUE TITLE
not an error, but perhaps nice to fix?

### ISSUE THREAD

**Issue by hugoledoux** [citygml4j/citygml-tools#2]
```
$ ./citygml-tools  --version
hallo
1.0
bla
```

**Comment by hugoledoux** [comment]
as you can see, it works fine and is über simple to use it.

only v0.6 output though? I can upgrade them with cjio though

**Comment by hugoledoux** [comment]
cheers!

**Comment by clausnagel** [comment]
Just released version [1.1.0](https://github.com/citygml4j/citygml-tools/releases/tag/v1.1.0).
