### ISSUE TITLE
Missing information in building function when converting to CityJSON

### ISSUE THREAD

**Issue by ozgetufan** [citygml4j/citygml-tools#25]
Hello, I converted a CityGML file to CityJSON where a building might have multiple functions, but in the CityJSON file only the first function is translated and the second one is missing. 

![image](https://user-images.githubusercontent.com/71127957/153832496-9ba97fb7-d0f9-4155-b924-71ba36c74d5d.png)

![image](https://user-images.githubusercontent.com/71127957/153832413-4fcadf79-3e15-48e5-9b26-21cbc81dba4c.png)

**Comment by clausnagel** [comment]
CityJSON 1.0 defines the property `"function"` of city objects to be a simple string (see [here](https://3d.bk.tudelft.nl/schemas/cityjson/1.0.3/cityobjects.schema.json)). And adding complex properties (i.e., objects or arrays) to  `"attributes"` requires an extension (see [here](https://www.cityjson.org/specs/1.0.3/#case-1-adding-new-complex-attributes-to-existing-city-objects)) that doesn't exist for CityGML attributes such as `bldg:function`.

So, there is not really another option for `citygml-tools` than the current implementation. You could use generic attributes in your CityGML instead (which is not recommended though). Or open an issue for CityJSON?!

**Comment by ozgetufan** [comment]
I will do that, thank you for your answer!
