### ISSUE TITLE
texture is missing after converting to CityJSON

### ISSUE THREAD

**Issue by hopezh** [citygml4j/citygml-tools#28]
I used the following command to convert all the CityGML files in a folder to CityJSON format. However it seems the texture mapping information is not exported at all. 

`./citygml-tools to-cityjson D:\test_CityGML_files\`

May I ask if there is a specific option in the citygmltools command that I need to use to export the texture?

Thanks.

**Comment by clausnagel** [comment]
Just did a test on my machine with some local test datasets and all appearance information was correctly translated to the CityJSON file. So, no issues here.

Please provide (an excerpt of) your CityGML data to be able to reproduce the issue.

**Comment by hopezh** [comment]
Thanks, @clausnagel for your reply. 

Unfortunately, the CityGML data I'm using is confidential, and I'm unable to provide a sample here. 

All I can share is the partial image of one of the CityJSON files obtained with sensitive information replaced by "???". 

![2022-06-28-11-22-18](https://user-images.githubusercontent.com/23435810/176104858-6a6dbd2b-5bdf-4b2f-98a3-1778d5e87d15.png)

What I want to ask is:

1. Can the texture (and texture mapping info such as which surface to use which texture and by which coordinates) be exported from CityGML to CityJSON using the citygml-tools? (Just like the conversion of CityGML to OBJ files, there will be a materials_textures folder generated to store the texture file used by the current model as shown below)

![2022-06-28-14-06-39](https://user-images.githubusercontent.com/23435810/176105374-3b6a6a53-3ea2-472c-a118-7ccd411dd9f8.png)

2. If yes, is there any particular option that I need to specify in the command line to achieve this? 

Thanks.

**Comment by clausnagel** [comment]
1: yes
2: no

The original texture files referenced from your CityGML input are reused. So, creating an additional "materials_textures" folder is not required.
