### ISSUE TITLE
doesn't export referenceSystem

### ISSUE THREAD

**Issue by strech345** [citygml4j/citygml-tools#3]
It looks like the referenceSystem in the metadata is missing. For me it only export the bbox.

**Comment by clausnagel** [comment]
GML supports multiple encoding schemes for spatial reference system names and there can be many different `srsName` attributes in the same CityGML file. So, automatically retrieving a unique EPSG code as required by CityJSON can become a tricky task. To support your request, I made the following changes to the `to-cityjson` operation (d90dffa376e3090e0bc29649dd921c1b1568ecac). 

First, the operation now tries to read the EPSG code from the CityGML file in the following way:
1. The `gml:Envelope` of the root `CityModel` is searched for a `srsName` attribute. 
2. If no `srsName` was found, then all envelopes of all top-level city objects contained in the `CityModel` are searched for an `srsName` attribute. All `srsName` attributes found must share the identical value.

If an `srsName` was found, then the following encoding schemes are supported to retrieve the EPSG code:

* http://www.opengis.net/def/crs/epsg/0/[EPSG code]
* urn:ogc:def:crs:EPSG:[version]:[EPSG code][,crs...]
* EPSG:[EPSG code]

Only if the `srsName` follows one of the above schemes, the EPSG will be written into the CityJSON file as metadata.

Second, and in addition to this automatic procedure, the user can now force a certain EPSG code to be used in the CityJSON file through the `--epsg=<code>` option. This is the recommended way if the EPSG code is known a priori.

Hope this helps. Both changes will be available in the next release.

**Comment by strech345** [comment]
Thanks. That sound good.

**Comment by clausnagel** [comment]
Just released version [1.1.0](https://github.com/citygml4j/citygml-tools/releases/tag/v1.1.0). Should be working now as outlined above. Can you please test and confirm?

**Comment by strech345** [comment]
Hallo Claus,
for me it change the epsg from (citygml)25832 to (json)3857
```
<?xml version="1.0" encoding="UTF-8"?>
<CityModel xmlns:smil20="http://www.w3.org/2001/SMIL20/" xmlns:grp="http://www.opengis.net/citygml/cityobjectgroup/1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:smil20lang="http://www.w3.org/2001/SMIL20/Language" xmlns:base="http://www.citygml.org/citygml/profiles/base/1.0" xmlns:luse="http://www.opengis.net/citygml/landuse/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:frn="http://www.opengis.net/citygml/cityfurniture/1.0" xmlns:tex="http://www.opengis.net/citygml/texturedsurface/1.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:bldg="http://www.opengis.net/citygml/building/1.0" xmlns:sch="http://www.ascc.net/xml/schematron" xmlns:app="http://www.opengis.net/citygml/appearance/1.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:gen="http://www.opengis.net/citygml/generics/1.0" xmlns:dem="http://www.opengis.net/citygml/relief/1.0" xmlns:wtr="http://www.opengis.net/citygml/waterbody/1.0" xmlns:tran="http://www.opengis.net/citygml/transportation/1.0" xmlns="http://www.opengis.net/citygml/1.0">
<gml:name>LoD1_496_6050_1_SH</gml:name>
<gml:boundedBy>
<gml:Envelope srsName="EPSG:25832" srsDimension="3">
<gml:lowerCorner>497141.625 6049454.116 0.897</gml:lowerCorner>
<gml:upperCorner>501338.219 6052916.669 38.695</gml:upperCorner>
</gml:Envelope>
</gml:boundedBy>
```

**Comment by clausnagel** [comment]
Thanks for testing. Yes, based on your snippet it seems that the converter works as expected. So I'm closing this issue. Feel free to re-open if you have further questions.
