### ISSUE TITLE
Appereance lost

### ISSUE THREAD

**Issue by ZehraKoc91** [citygml4j/citygml-tools#34]
Hi,

I have used the tool for converting CityGML data (which is textured) to CityJSON. 
![1](https://user-images.githubusercontent.com/61785114/205002356-17ef4f98-dad3-488d-a851-5e542c5b0fc8.JPG)

After the process ended, using FME inspector I have realized that some textures are missing. Do you have any recommendations about this? 
![2](https://user-images.githubusercontent.com/61785114/205002951-c8e923b1-9a92-4724-a8a5-b016d6ae311f.JPG)

**Comment by clausnagel** [comment]
@ZehraKoc91 can you please provide a test dataset so that we can reproduce the issue?

**Comment by ZehraKoc91** [comment]
https://drive.google.com/file/d/166njbkDJZBbrajnigmZKUhq4_ON-nPRC/view?usp=sharing

Hi, I just added my file, which you can find above. There were similar data in less MB but these worked well on conversion actually. That's why I send you the original data instead of the test data with less number of buildings.

**Comment by ZehraKoc91** [comment]
The problem is fixed. Appereance folder was holding less data than expected. Thank you.

**Comment by Aloneking-34** [comment]
💫
