### ISSUE TITLE
Question: conversion of citygml with gfs file

### ISSUE THREAD

**Issue by Marwa-AL** [citygml4j/citygml-tools#43]
Hi all, 

I am working with 3D building data from BayrenAtlas. The data are downloaded in tiles each tile has .gml and .gfs file. I converted the CityGML file to CityJSON for further analysis in Python. However, I noticed a scaling and shift in the data after starting the analysis. 

Example: the actual surface area is 15 but I get an area of 15e-5. Also the vertices are shifted out of the geographical extent. 

Do you have any idea what could be wrong? Is it possible that some data are missed during the conversion. 

Thank you

**Comment by clausnagel** [comment]
Try and convert to CityJSON 1.0 instead. In this conversion, do not transform the coordinates (so, do not use the `--transform-ccordinates` option). 

    > citygml-tools to-cityjson --cityjson-version=1.0 /your/CityGML/file.gml

This way, the resulting CityJSON output file will contain the original coordinates and not transformed ones. If there is still a shoft, check #37.

**Comment by Marwa-AL** [comment]
It worked. Thank you very much.
