### ISSUE TITLE
Extensions support for conversion from CityJSON to CityGML

### ISSUE THREAD

**Issue by ElTure97** [citygml4j/citygml-tools#49]
Hi all,

For my master degree thesis, I developed a data management pipeline whose objective is the one of outputting a CityJSON file for further conversion into CityGML with both Energy and Utility Network extensions according to the following schemas:

Energy:
https://github.com/ozgetufan/cjenergy/blob/master/schemas/extensions/energy.ext.json
Utility:
https://github.com/idiap/cjutilitynetwork/blob/main/utilitynetwork.ext.min.json

I would like to know if that tool enables the conversion from CityJSON with those extensions, to CityGML with respective ADEs.

Thank you in advance

**Comment by clausnagel** [comment]
No, there is no fully automatic mapping between CityJSON extensions and CityGML ADEs. `citygml-tools` converts CityJSON extensions to generic city objects and attributes in CityGML by default.

If you really want to convert into a CityGML ADE, you have to implement a corresponding extension module for `citygml4j` and use it with `citygml-tools`. Not really difficult but requires Java programming.

**Comment by ElTure97** [comment]
Thank you for the clarifications!

> No, there is no fully automatic mapping between CityJSON extensions and CityGML ADEs. `citygml-tools` converts CityJSON extensions to generic city objects and attributes in CityGML by default.
> 
> If you really want to convert into a CityGML ADE, you have to implement a corresponding extension module for `citygml4j` and use it with `citygml-tools`. Not really difficult but requires Java programming.
