### ISSUE TITLE
support for CityJSON v2.0

### ISSUE THREAD

**Issue by hugoledoux** [citygml4j/citygml-tools#50]
it's so minor it will take you 5min: https://www.cityjson.org/dev/upgrade20/

https://www.cityjson.org/specs/2.0.0/

thanks!

**Comment by clausnagel** [comment]
Added support for CityJSON 2.0 in citygml4j with https://github.com/citygml4j/citygml4j/commit/747c4f48f6d1cd985e547996d893a1d01f2b50ba. Most of the work has been done with this. I first have to publish a new citygml4j release before updating citygml-tools. Stay tuned.

**Comment by clausnagel** [comment]
Just released [citygml-tools 2.2.0](https://github.com/citygml4j/citygml-tools/releases/tag/v2.2.0) with support for CityJSON 2.0. Closing this issue.
