### ISSUE TITLE
how to pull image on arm64

### ISSUE THREAD

**Issue by jessymatar** [citygml4j/citygml-tools#52]
docker pull citygml4j/citygml-tools

Raises the below error:

Using default tag: latest
latest: Pulling from citygml4j/citygml-tools
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by clausnagel** [comment]
Adapted workflow files with 3726c46162a684f16d0a3cff5cb4150b818f67df.
@jessymatar, please test again using `edge` as tag (`docker pull citygml4j/citygml-tools:edge`).

**Comment by clausnagel** [comment]
Added another fix with 5d102844ae820622d5a85a7e2103137963737ec3. Closing this issue now. Feel free to reopen if the problem still exists
