### ISSUE TITLE
 Check the structure citygml  By object 

### ISSUE THREAD

**Issue by Pdongjaelee** [citygml4j/citygml-tools#53]
I converted ifc to citygml.

I want to compare ifc objects and citygml objects converted from ifc.

Is there a way?

**Comment by clausnagel** [comment]
This is beyond the scope of citygml-tools. Maybe a tool like [FME](https://fme.safe.com/) can help you.

**Comment by Pdongjaelee** [comment]
So is there any way to view citygml using citygml-tools?

**Comment by clausnagel** [comment]
No, citygml-tools is not a viewer. Maybe give the [KITModelViewer](https://www.iai.kit.edu/1302.php) a try. It's a free viewer that can load both IFC and CityGML. Also FME mentioned above can view both formats.

**Comment by Pdongjaelee** [comment]
Can citygml-tools simply convert?

**Comment by clausnagel** [comment]
You mean from IFC to CityGML? I like your "simply" in this context ;-) No, again, beyond the scope of citygml-tools.

Again, you can use FME to implement such a conversion (so it seems we are narrowing it down to this tool). The KITModelViewer can also load IFC and save as CityGML. [BIM Base](https://bimbase.nl/) can do it. And there are more tools which I am not aware of...

**Comment by clausnagel** [comment]
Closing because citygml-tools is not the right tool for the requested operation. Feel free to open a [discussion](https://github.com/citygml4j/citygml-tools/discussions) in case you have more questions.

**Comment by Pdongjaelee** [comment]
Oh, I have one more question.
I have now converted ifc using citygml-tools.

Is this citygml3.0?
Or is it citygml3.0 ADE?

**Comment by clausnagel** [comment]
If you share your converted file (or just an excerpt of it), I can tell you what your CityGML output is. Which tool have you used for the conversion? citygml-tools doesn't offer IFC to CityGML, so must have been something else.

**Comment by Pdongjaelee** [comment]
![image](https://github.com/citygml4j/citygml-tools/assets/111861625/5bf9bc31-88d0-4ce3-b9c1-d373a790319c)

This file is a file converted from IFC to Cityjson and then to citygml.

This is the first part of the file. Do you need more information?

I can't upload this file itself here.

**Comment by clausnagel** [comment]
Ok, gotcha. When converting CityJSON to CityGML with citygml-tools, the output is CityGML 3.0 by default. Your file is also CityGML 3.0.

citygml-tools does neither process nor create ADEs without a specific software extension (an additional JAR file that gets loaded when citygml-tools is started). I guess you don't have such an extension, which means your output is plain CityGML 3.0 without any ADE content.

Does your CityJSON input file contain a `CityJSON Extension`? The easiest way to find out is probably to validate your file with this online tool: https://validator.cityjson.org/. If it contains an extension, this extension might also be not fully processed by citygml-tools without a corresponding software extension.
