### ISSUE TITLE
Unreasonably long time (possibly dead loop) to convert some gml files

### ISSUE THREAD

**Issue by zhou13** [citygml4j/citygml-tools#8]
It takes unreasonably long time (possibly dead loop) to convert https://drive.google.com/file/d/1rP5P7W3dTiP9vK9VrxvWK5dqO5QIrvWw/view?usp=sharing. Normally citygml-tool will finish the conversion task in several minutes but for this file, it takes forever (48+ hours and it is still running)

**Comment by clausnagel** [comment]
Yes, you are right. The program ran into an infinite loop. I fixed citygml4j (https://github.com/citygml4j/citygml4j/commit/54f28afe3079b3a88a8f8da86a1c65e038534658) and updated the `master` branch. So you can build a new version following these [instructions](https://github.com/citygml4j/citygml-tools#building).

Please also check your dataset. It contains a lof of issues (such as schema violations, unclosed rings, invalid rings, invalid solids, invalid XLinks, invalid mix of CityGML 1.0 and 2.0).

Some polygons share the same `gml:id` which is not allowed (`gml:id`s must be unique per dataset). And then there are XLink references to these duplicate `gml:id`s. Such references cannot be resolved unambiguously and may lead to unexpected issues. This was one reason for the infinite loop. Well, it even seems that entire buildings are redundantly stored in the dataset?

**Comment by clausnagel** [comment]
Just published [version 1.3.2](https://github.com/citygml4j/citygml-tools/releases/tag/v1.3.2) which contains the fix. So closing this issue.
