### ISSUE TITLE
Can't run citygml-tools

### ISSUE THREAD

**Issue by rauschbe** [citygml4j/citygml-tools#9]
Hey guys,

unfortunately I am not able to run the tool. I followed the instructions and tried to open "citygml-tools" in the bin folder. 

The command line gets opened but ends the process immediately:

`citygml-tools ; exit;
Missing required subcommand.
Usage: citygml-tools [-hV] [--log=<level>] [COMMAND]
Collection of tools for processing CityGML files.
      --log=<level>   Log level: error, warn, info, debug (default: info).
  -h, --help          Show this help message and exit.
  -V, --version       Print version information and exit.
Commands:
  help              Displays help information about the specified command
  change-height     Changes the height values of city objects by a given offset.
  remove-apps       Removes appearances from city objects.
  move-global-apps  Converts global appearances to local ones.
  clip-textures     Clips texture images to the extent of the target surface.
  filter-lods       Filters the LoD representations of city objects.
  reproject         Reprojects city objects to a new spatial reference system.
  from-cityjson     Converts CityJSON files into CityGML.
  to-cityjson       Converts CityGML files into CityJSON.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process terminated]`

Any suggestions where the line "Missing required subcommand" comes from? I installed Java through homebrew. Could this cause the issue?

Best,
Benni

**Comment by derhuerst** [comment]
Apparently the `citygml-tools` CLI has to be used via sub-commands, e.g. `to-cityjson`. In the message that you copy-pasted, it gives you a list of possible sub-commands:

```

help Displays help information about the specified command
change-height Changes the height values of city objects by a given offset.
remove-apps Removes appearances from city objects.
move-global-apps Converts global appearances to local ones.
clip-textures Clips texture images to the extent of the target surface.
filter-lods Filters the LoD representations of city objects.
reproject Reprojects city objects to a new spatial reference system.
from-cityjson Converts CityJSON files into CityGML.
to-cityjson Converts CityGML files into CityJSON.
```

**Comment by clausnagel** [comment]
@derhuerst explained it correctly. You have to specify a subcommand to run `citygml-tools`.

Open a console, switch to the `bin` folder and type the following to get a list of the available subcommands:

    $ citygml-tools --help

For instance, to convert CityGML files into CityJSON, use the subcommand `to-cityjson`. To see the possibilities of the `to-cityjson` subcommand, type the following.

    $ citygml-tools to-cityjson --help

Hope this helps.

**Comment by rauschbe** [comment]
I see that is great! Thanks so much for the explanation!
